config/routes.rb
PositivKompetanse::Application.routes.draw do
    get "users/new"

    root 'static_pages#home'
    match  '/signup', to: 'users#new', via: 'get'
    match  '/tjenester', to: 'static_pages#tjenester', via: 'get'
    match  '/about', to: 'static_pages#about', via: 'get'
    match  '/contact', to: 'static_pages#contact', via: 'get'
    match  '/rekruttering', to: 'static_pages#rekruttering', via: 'get'

  end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
 	validates :name, presence: true, length: { maximum: 50 }
 	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def tjenester
  end
  
  def about
  end
  
  def rekruttering
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title)                          # Method definition
    base_title = "Positiv Kompetanse"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{base_title} | #{page_title}"                 # String interpolation
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://icity.no/">positivkompetanse.no</a>
    by M.F.B
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Positiv Kompetanse", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",   	root_path    %></li>
					<li><%= link_to "Tjenester", tjenester_path    %></li>
					<li><%= link_to "Om Oss",  	about_path   %></li>
					<li><%= link_to "Contact",	contact_path %></li>
					<li><%= link_to "Rekruttering", 	rekruttering_path %></li>
					<li><%= link_to "Sign", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
	<body>
		<%= render 'layouts/header' %>
		<div class= "container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'Om oss')%>
<div class="center hero-unit">
	<h1>Om Oss</h1>
		<%= link_to image_tag("logo.png", alt: "pk_logo"), root_path %>
		<h3>En lokal rekrutteringsrådgiver med solid erfaring innen rekruttering og rådgivning, og med et godt opparbeidet nettverk hos kunder og arbeidssøkende.</h3> <p> Positiv Kompetanse fokuserer på ekte engasjement, lojalitet, positivitet og kvalitet! Vi utfører rekruttering og rådgivnings oppdrag i hele Norden. Vi gjennomfører både hele og deler av rekrutteringsprosessen for våre kunder, men i de fleste tilfeller tar vi hele oppgaven fra A til Å.</p>
			<%= link_to "Contact", contact_path, class: "btn btn-primary btn-large" %>
		</p>

</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%>
<h1>Contact Us</h1>

<p>Firmaanalyse</p>

Når et selskap med sine tall og ressurser skal vurderes for 

oppkjøp er det alt for ofte at menneskene i selskapet får at for lite 

oppmerksomhet. Kultur, uro, kunnskapsnivå, nettverk, holdninger, 

personlige konflikter, og ikke minst interne oppleveleser av muligheter 

og tanker vil kunne bidra til en mest riktig vurdering for et lønnsomt og 

mest suksess fult oppkjøp! Vi kan bidra med vår kunnskap og erfaring 

med å utarbeide et mer oversiktlig og riktig grunnlag for å ta rette 

avgjørelse når alt kommer til alt! 

 

Vår vurdering vil gi deg en mye bredere og riktig mulighet til å kjøpe 

verdi med både personlig og økonomisk verdi!

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>Help</h1>
	<p>
		Need help, check out this site
		<a href="http://www.icity.no">www.icity.no</a>
	</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

  <h1>Grip sjansen idag....</h1>
 	<%= link_to image_tag("logo.png", alt: "pk_logo"), root_path %>
    <h3>
    	Ny jobb?
    	Nye muligheter?<br>
    	Nye løsninger
    	Nye folk?<br>
    	Gjør noe positivt med din kompetanse.

    	Registrer deg her.
  	</h3>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-success btn-large" %>
</div>
<!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h3>Formidling</h3>
          	<p>1. Gjennomgang av kompetanse behov sammen med kunde. <br>
			 	2. Kunde får tilgang og oversendt kandidater som PK til en hver tid kommer over med ønsket erfaring og kvalifikasjoner.
		  	</p>
          <p><a class="btn" href="#">Les mer &raquo;</a></p>
        </div>
        <div class="span4">
          <h3>Rådgivning</h3>
          	<p> 1. Vi kan bistå våre kunder med personal spørsmål og rådgivning i forhold til interne utfordringer. <br>
			 	2. 
			<br><br>
			<br>
		  	</p>
          <p><a class="btn" href="#">Les mer &raquo;</a></p>
       </div>
        <div class="span4">
          <h3>Rekruttering</h3>
          <p>Jobbanalyse

		Annonsering - Search<br>

		1 gangs intervju & 2 gangs intervju <br>

		Kandidatpresentasjoner til kunde <br>

		3 gangs intervju hos kunde <br>

		Referanseintervjuer<br>

		Ansettelse - Oppfølging</p>
          <p><a class="btn" href="#">Les mer &raquo;</a></p>
        </div>
      </div>

app/views/static_pages/jobs.html.erb
<%provide(:title, "Jobs")%>

<h1>(H1)Jobs page</h1>
	<h2>(H2)<%= "Velkommen, idag er det #{Time.now.strftime('%A')}  #{@morten}"%></h2>
		<h3>(H3)<%= @morten%></h3>
			<h4>(H4)Ja ja ja sand</h4>
				<p>(P)<a href="http://www.icity.no">www.icity.no</a></p>

app/views/static_pages/rekruttering.html.erb
<%provide(:title, "Rekruttering")%>
<div class="center hero-unit">
<h1>Rekruttering</h1>
	<h3>
		Jobbanalyse<br><br>
		Annonsering - Search<br><br>
		1 gangs intervju & 2 gangs intervju <br><br>
		Kandidatpresentasjoner til kunde <br><br>
		3 gangs intervju hos kunde <br><br>
		Referanseintervjuer - Ansettelse <br><br>
		Oppfølging

			</h3>
</div>

app/views/static_pages/tjenester.html.erb
<% provide(:title, 'Tjenester')%>
<div class="center hero-unit">
	<h1>Tjenester</h1>
		<h3>
			<ul>
				Rekruttering<br><br>
				Formidling<br><br>
				Rådgivning<br><br>
				Firmaanalyse
			</ul>
		</h3

</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>